### ISSUE TITLE
botnamens konvention

### ISSUE THREAD

**Issue by lukruh** [telebotter/telebotter#19]
sollen wir uns zur vereinheitlichung auf eine schreibweise fuer bot namen und bot usernamen einigen? Daneben auch fuer die repositories (github.com/telebotter/`reponame`) und ggf. websites (telebotter.sarbot.de/`websitename`). 

Eine Option waere fuer alles den botusernamen zu nehmen, welcher sich aber auch aendern kann.. deshalb vlt. doch lieber ein projektname + schoener name (mit leerzeichen gross/klein) + botusername.

**Comment by lukruh** [comment]
wenn projektname nicht zwangslaeufig botname ist finde ich klein zusammengeschrieben deutsch gut. Deutsch, weil man dann aehnlich botnamen sein kann englische namen sind quasi alle vergeben xD. und weil sprache eh haupts. deutsch ist.

Projekt: `projektname`
Botusername: `projektnamebot`
Botname: `:) Projekt Name Bot`
websitename: `projektname`

**Comment by hendricokakiko** [comment]
jo finde gut

**Comment by lukruh** [comment]
oder username = ProjektNameBot.. aber ich find alles klein irgendwie schoener..
dann nehm ich das mal so als richtlinie fuer zukuenfitige bots auf, aber aendere die die schon da sind erstmal nicht
